# 1. H2 資料庫連線設定 (加上 AUTO_SERVER=TRUE 允許 DBeaver 同時連線)
spring.datasource.url=jdbc:h2:file:./data/smartstaydb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. JPA/Hibernate 基礎設定
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 3. 開啟 H2 控制台
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console